# Generated by Django 5.0.6 on 2024-05-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20240513_1201'),
    ]

    operations = [
        migrations.RunSQL(
            sql=""" 
            WITH delivery_time AS (
                    SELECT orders_order.id, (round(point(orders_order.latitude, orders_order.longitude)<->point(
                    orders_order.fastfood_id.latitude, orders_order.fastfood_id.longitude))*3 + 
                    round((orders_order.order_items_id.quantity)/4)*5) as delivery_time
                    FROM orders_order
                    ORDER BY orders_order.id ASC
                    )
                    SELECT *
                    FROM orders_order
        """,
            reverse_sql="ALTER TABLE orders_order DROP orders_orderitem",
        )
    ]
