# Generated by Django 5.0.6 on 2024-05-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=13, max_digits=17, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=13, max_digits=17, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FastFoodParent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fastfood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastfood', to='fastfoods.fastfood')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastfoodparent', to='products.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
